### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by hawkinsw** [brennie/fxrecord#2]
Not sure if/how I can make a review, so I am just going to do it here:

1. In the `README.md`, can you clarify that this tool /parses configuration files/ and invokes a function that the user customizes that will actually take the action based on that configuration?  I know that's a subtle distinction, but it was something that really confused me as I looked at the code. 
1. I really like the refactor into the `run` function that collects the parsing logic and then invokes a function that the user can customize to take action based on that parsed configuration.

I planned on writing more in this first round, but I got distracted by reading your code and learning some things about Rust that I never knew. I will continue tomorrow, I promise :-)

**Comment by freshstrangemusic** [comment]
> Not sure if/how I can make a review, so I am just going to do it here:
> 
> 1. In the `README.md`, can you clarify that this tool /parses configuration files/ and invokes a function that the user customizes that will actually take the action based on that configuration?  I know that's a subtle distinction, but it was something that really confused me as I looked at the code.

As we discussed, it isn't really a user-customizable thing. Just that the actual guts of this haven't been written yet, so the `fxrecorder()` and `fxrunner()` methods are stubs at the moment.

> 2. I really like the refactor into the `run` function that collects the parsing logic and then invokes a function that the user can customize to take action based on that parsed configuration.

Thanks! I think it was a good refactor, too.

> I planned on writing more in this first round, but I got distracted by reading your code and learning some things about Rust that I never knew. I will continue tomorrow, I promise :-)

Thanks for the review!
